apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k8s-dashboard
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: staging-cluster
    namespace: monitoring
  project: default
  source:
    path: ./Applicationset/charts/monitoring/k8s-dashboard
    repoURL: https://github.com/tanmay-bhat/ArgoCD.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    


