apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-exporter
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  project: default
  source:
    path: ./Applicationset/charts/monitoring/node-exporter
    repoURL: https://github.com/tanmay-bhat/ArgoCD.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true    
