# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

pln-chart:  
  nginx:
    replicaCount: 1
    image:
      repository: nginx
      pullPolicy: Always
      # Overrides the image tag whose default is the chart appVersion.
      tag: "1.18"
    kafka:
      topics:
        - {ref_name: port-prov-in, var_name: port_prov_incomming_pluskcleo_1, alc: "", auto_create: , partitions: ""}
        - {ref_name: PORT-PROV-OUT, var_name: port_prov_outgoing_pluskcleo-1, alc: "", auto_create: , partitions: ""}
        - {ref_name: test, var_name: port_prov_outgoing_pluskcleo-1, alc: "", auto_create: "", partitions: ""}
  
  
  imagePullSecrets:
    - name: "ghcr-io-credentials"
  nameOverride: ""
  fullnameOverride: ""
  
  serviceAccount:
    # Specifies whether a service account should be created
    create: false
    # Annotations to add to the service account
    annotations: {}
    # The name of the service account to use.
    # If not set and create is true, a name is generated using the fullname template
    name: ""
  
  podAnnotations: {}
  
  podSecurityContext: {}
    # fsGroup: 2000
  
  securityContext: {}
    # capabilities:
    #   drop:
    #   - ALL
    # readOnlyRootFilesystem: true
    # runAsNonRoot: true
    # runAsUser: 1000
  
  service:
    type: ClusterIP
    port: 80
  
  ingress:
    enabled: false
    className: ""
    annotations: {}
      # kubernetes.io/ingress.class: nginx
      # kubernetes.io/tls-acme: "true"
    hosts:
      - host: chart-example.local
        paths:
          - path: /
            pathType: ImplementationSpecific
    tls: []
    #  - secretName: chart-example-tls
    #    hosts:
    #      - chart-example.local
  
  ingressRoutes:
    enabled: true
    apiVersion: traefik.containo.us/v1alpha1
    paths:
      - { name: soa, match: Host(`devops-test.soacleo.plusk.plusnet.de`) }
      #- { name: azsoa, match: Host(`devops-test.azsoacleo.plusk.plusnet.de`) }
      - { name: app, match: Host(`devops-test.appcleo.plusk.plusnet.de`) }
      - { name: azapp, match: Host(`devops-test.azappcleo.plusk.plusnet.de`) }
  
  resources: {}
    # We usually recommend not to specify default resources and to leave this as a conscious
    # choice for the user. This also increases chances charts run on environments with little
    # resources, such as Minikube. If you do want to specify resources, uncomment the following
    # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
    # limits:
    #   cpu: 100m
    #   memory: 128Mi
    # requests:
    #   cpu: 100m
    #   memory: 128Mi
  
  autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
